# config/packages/api_platform.yaml
api_platform:
    title: 'Drink Water REST API'
    description: 'A Symfony API to manage users and devices.'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header